disabled_rules:
- line_length
- trailing_whitespace
- nesting
- function_parameter_count
- function_body_length
- cyclomatic_complexity
- file_length
- identifier_name
- empty_count
- force_cast
- type_name
- shorthand_operator
- switch_case_alignment
- for_where
- comma
- opening_brace


excluded:
  - .github/workflows/swift.yml
  - Pods
  - ../Pods
  - ./Pods
  - /Pods
  - Project/R.generated.swift
  - Project/Pods
  - BeMyPlan/AppDelegate.swift
  - BeMyPlan/SceneDelegate.swift
  - BeMyPlan/Screen/Plan/PlanDetail/PlanDetailVC + setPreviewDummy.swift
