

force_cast: # From https://realm.github.io/SwiftLint/force_cast.html
    warning
    
    
function_body_length:
    error:  200

trailing_whitespace:
    ignores_empty_lines: true
    
line_length:
    error:   100
    
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 30
    error: 40
    

force_cast: warning
force_try: warning

disabled_rules: # Default Rules에서 비활성화할 규칙
    
    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
    - trailing_whitespace
    - shorthand_operator
    - identifier_name
    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
    - force_unwrapping
    - weak_delegate
    - opening_brace
    - unused_optional_binding
    - statement_position
    - switch_case_alignment
    - nesting
    - colon
    - orphaned_doc_comment
    - unused_closure_parameter
    - private_over_fileprivate
    - empty_enum_arguments
    - line_length
    - comma
    - void_return
    - vertical_parameter_alignment
    - unused_enumerated
    - control_statement
    - force_cast


### 배열을 사용해 warning과 error의 수준을 모두 설정할 수 있습니다.
type_body_length:
  warning: 300 # warning, implicitly
  error: 400 # error, implicitly

file_length:
  warning: 200
  error: 400
  
vertical_whitespace:
  warning: 3
  error: 5
  
  

excluded:
  - Pods
  - ../Pods
  - ./Pods
  - /Pods
  - Project/R.generated.swift
  - Project/Pods
  - BeMyPlan/AppDelegate.swift
  - BeMyPlan/SceneDelegate.swift
