disabled_rules:
- line_length
- trailing_whitespace
- nesting
- function_parameter_count
- function_body_length
- cyclomatic_complexity
- file_length

opt_in_rules:
- empty_count
- empty_string

excluded:
  - Pods
  - ../Pods
  - ./Pods
  - /Pods
  - Project/R.generated.swift
  - Project/Pods
  - BeMyPlan/AppDelegate.swift
  - BeMyPlan/SceneDelegate.swift
  - BeMyPlan/Screen/Plan/PlanDetail/PlanDetailVC + setPreviewDummy.swift
