# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'BeMyPlan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeMyPlan

  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftLint'
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 카카오 로그인
  pod 'KakaoSDKUser'  # 사용자 관리
  pod 'lottie-ios'
  pod 'Kingfisher', '~> 5.0'
  pod 'Then'
  pod 'Moya'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'PanModal'
  pod 'SkeletonView'
   pod 'ImageSlideShowSwift', :git => 'https://github.com/TeamBeMyPlan/ImageSlideShow.git', :branch => 'master'
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'RxGesture'
   pod 'RxRelay'
end
