# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "BeMyPlan.xcodeproj")
    build_app(
      export_xcargs: "-allowProvisioningUpdates",
      workspace: "BeMyPlan.xcworkspace", 
      scheme: "BeMyPlan")
      slack(
      message: "비마이플랜이 App Store Connect TestFlight에 성공적으로 업로드 되었습니다.",
      success: true,
      slack_url: "https://hooks.slack.com/services/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"
    )
    upload_to_testflight
  end
end



increment_build_number( build_number: latest_testflight_build_number + 1, xcodeproj: "BeMyPlan.xcodeproj" )
