name: Swift

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cocoapod Install
      run: pod install --repo-update
    
    - name: Run tests
      run:
        pod install --repo-update --clean-install --project-directory=BeMyPlan/
        xcodebuild clean test -workspace BeMyPlan/BeMyPlan.xcworkspace -scheme BeMyPlan -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
