name: Swift

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches:    
      - dev
      - 'feature/**'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Start xcode build 🛠
      run: |
        pod install --repo-update --clean-install --project-directory=BeMyPlan/
        xcodebuild clean build -workspace BeMyPlan/BeMyPlan.xcworkspace -scheme BeMyPlan -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
